# Generated by Django 4.1 on 2023-09-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menuchangeandprices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuchangeandprices',
            old_name='catecory',
            new_name='category',
        ),
    ]
